Initialize Project
mohametalmeari/bookstore pull request #1
Opened 2023-06-06 11:32 UTC by mohametalmeari

- [ ] Install React 
- [ ] Setup Linters
- [ ] Create Routes 
- [ ] Create Components 
- [ ] Style

2023-06-06 13:14 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @mohametalmeari,

Good job so far!
✔️ Books component is the index route
✔️ Reusable components implementation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 13:14 UTC, TedLivist commented on src/components/Book.js
> +const Book = () => (
- [ ] The Book component should be set up so that it takes in the book data as prop and renders the title and author.

  ```
  const Book = ({title, author}) => (
    ...
  )
  ```

2023-06-06 13:59 UTC, danmainah approved these changes
Hi @mohametalmeari , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ Linter setup correctly and all checks are passing
✔️  Good design on your book page

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 14:01 UTC, merged

2023-06-10 08:17 UTC, mohametalmeari commented
Thanks a lot 🙏